### ISSUE TITLE
add travis

### ISSUE THREAD

**Issue by timelyportfolio** [r-spatial/leafpm#1]
@edzer would it be possible to add `leafpm` to r-spatial Travis?  Thanks so much.

**Comment by edzer** [comment]
The setup for this has changed, and I don't know where this is now. @tim-salabim would you mind doing this?

**Comment by tim-salabim** [comment]
I'll see what I can do. Though the mapview setup is currently failing as is sf (as I just saw). Maybe @pat-s can help here (and elsewhere)?

**Comment by pat-s** [comment]
I'll take a look this evening!

**Comment by pat-s** [comment]
I do not have access to the Travis account for the r-spatial org. Happy to make all the required changes if someone adds me.
Other than that, I recommend using [tic](https://github.com/ropenscilabs/tic) which is also used in _sf_ and _mapview_. The setup can be adapted from these projects or from the [example package repo](https://github.com/ropenscilabs/tic.package).

**Comment by edzer** [comment]
I added the web hook. I'll make you admin if anything is missing.

**Comment by pat-s** [comment]
`travis::use_tic` should eventually work OOB if the package and its dependencies are "simple" enough. Call it with admin rights from the repo root, that's the easiest start.

**Comment by tim-salabim** [comment]
OK will try

**Comment by tim-salabim** [comment]
First build has passed :+1:

**Comment by timelyportfolio** [comment]
Thanks @edzer @pat-s @tim-salabim.  Looks like travis is up and running.
